version: '3.8'

services:
  statesync:
    build: .
    container_name: statesync
    restart: unless-stopped
    environment:
      - STATESYNC_EMBY_URL=http://192.168.3.3:8096
      - STATESYNC_EMBY_API_KEY=364ac7c91b5348c3a2b15fbf5b2601ad
      - STATESYNC_JELLYFIN_URL=http://192.168.3.10:8096
      - STATESYNC_JELLYFIN_API_KEY=e9f0c48ceaa94742a69b8263d4773b2f
      - STATESYNC_SYNC_THRESHOLD_SECONDS=5
      - RUST_LOG=info

    # Alternative: Mount a config.json volume instead of using env variables
    # volumes:
    #   - ./config.json:/etc/statesync/config.json:ro
