version: '3.8'

services:
  statesync:
    build: .
    container_name: statesync
    restart: unless-stopped
    ports:
      - "8754:8754"
    volumes:
      - ./config:/config
    environment:
      - RUST_LOG=info
